# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quiver.fullname" . }}
  labels:
    app: {{ include "quiver.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "quiver.name" . }}
